In [1]:
import pandas as pd

oof_df = pd.read_csv('oof_df.csv')
oof_df.head()

,discourse_id,essay_id,discourse_text,discourse_type,discourse_effectiveness,pred_ineffective,pred_adequate,pred_effective,label,loss,prob_seq
0,0013cc385424,007ACE74B050,"Hi, i'm Isaac, i'm going to be writing about h...",Lead,Adequate,0.038339,0.929532,0.032129,1,0.073074,[[0.22914091 0.7545275 0.01633158]\n [0.22914...
1,9704a709b505,007ACE74B050,"On my perspective, I think that the face is a ...",Position,Adequate,0.078184,0.874242,0.047574,1,0.134398,[[0.15318474 0.82462126 0.02219396]\n [0.19805...
2,c22adee811b6,007ACE74B050,I think that the face is a natural landform be...,Claim,Adequate,0.405734,0.586073,0.008193,1,0.534311,[[0.3005016 0.68630135 0.01319703]\n [0.53834...
3,a10d361e54e4,007ACE74B050,"If life was on Mars, we would know by now. The...",Evidence,Adequate,0.243247,0.744494,0.012259,1,0.295051,[[0.3588545 0.63167965 0.00946586]\n [0.62148...
4,db3e453ec4e2,007ACE74B050,People thought that the face was formed by ali...,Counterclaim,Adequate,0.447142,0.546738,0.006120,1,0.603785,[[0.37385288 0.616179 0.00996815]\n [0.39356...

In [2]:
oof_df = oof_df.rename(columns={
    'pred_ineffective':'Ineffective',
    'pred_adequate':'Adequate',
    'pred_effective':'Effective'
})
oof_df[['discourse_id','Ineffective','Adequate','Effective']].to_csv(f'oof_Tom_768_512_128.csv', index=False)

In [3]:
pd.read_csv(f'oof_Tom_768_512_128.csv').head()

   discourse_id  Ineffective  Adequate  Effective
0  0013cc385424     0.038339  0.929532   0.032129
1  9704a709b505     0.078184  0.874242   0.047574
2  c22adee811b6     0.405734  0.586073   0.008193
3  a10d361e54e4     0.243247  0.744494   0.012259
4  db3e453ec4e2     0.447142  0.546738   0.006120