In [1]:
import pandas as pd

local_pred_df  = pd.read_csv('stack_99_v1_02_04.csv')
kaggle_pred_df = pd.read_csv('kaggle_stack_df_99_v1_02_04.csv')

In [2]:
fold_path = '../../../00_EDA/00_v2_07/result/'

import joblib
print('load folds...')
from os.path import join as opj
val_ids_list = joblib.load(opj(fold_path,f'val_ids_list.joblib'))

fold = 0

local_pred_df = local_pred_df[local_pred_df['essay_id'].isin(val_ids_list[fold])].reset_index(drop=True)
kaggle_pred_df = local_pred_df[['discourse_id']].merge(kaggle_pred_df, on='discourse_id', how='left').reset_index(drop=True)

load folds...

In [3]:
local_pred_df.shape, kaggle_pred_df.shape

((7303, 22), (7303, 16))

In [4]:
local_pred_df.head()

,discourse_id,essay_id,discourse_text,discourse_type,discourse_effectiveness,Ineffective_0,Adequate_0,Effective_0,label,loss,...,Effective_1,Ineffective_2,Adequate_2,Effective_2,Ineffective_3,Adequate_3,Effective_3,Ineffective,Adequate,Effective
0,0013cc385424,007ACE74B050,"Hi, i'm Isaac, i'm going to be writing about h...",Lead,Adequate,0.005362,0.149828,0.011476,1,0.106507,...,0.004528,0.004350,0.305959,0.023024,0.010763,0.308277,0.014293,0.032391,0.914288,0.053322
1,9704a709b505,007ACE74B050,"On my perspective, I think that the face is a ...",Position,Adequate,0.017125,0.147905,0.001637,1,0.119425,...,0.002962,0.018665,0.305458,0.009210,0.017491,0.307105,0.008737,0.062665,0.914790,0.022546
2,c22adee811b6,007ACE74B050,I think that the face is a natural landform be...,Claim,Adequate,0.045510,0.120447,0.000710,1,0.324790,...,0.001230,0.046903,0.282717,0.003714,0.084472,0.245645,0.003216,0.211918,0.779213,0.008870
3,a10d361e54e4,007ACE74B050,"If life was on Mars, we would know by now. The...",Evidence,Adequate,0.034794,0.130030,0.001843,1,0.248233,...,0.001894,0.111466,0.218990,0.002878,0.079564,0.249848,0.003921,0.258692,0.730773,0.010535
4,db3e453ec4e2,007ACE74B050,People thought that the face was formed by ali...,Counterclaim,Adequate,0.052472,0.113541,0.000653,1,0.383832,...,0.000738,0.082580,0.249347,0.001406,0.114735,0.216563,0.002036,0.319503,0.675664,0.004833

In [5]:
kaggle_pred_df.head()

,discourse_id,Ineffective_0,Adequate_0,Effective_0,Ineffective_1,Adequate_1,Effective_1,Ineffective_2,Adequate_2,Effective_2,Ineffective_3,Adequate_3,Effective_3,Ineffective,Adequate,Effective
0,0013cc385424,0.005362,0.149828,0.011476,0.011916,0.150223,0.004528,0.004348,0.305961,0.023024,0.010757,0.308274,0.014303,0.032383,0.914286,0.053331
1,9704a709b505,0.017125,0.147905,0.001637,0.009383,0.154322,0.002962,0.018664,0.305459,0.009209,0.017479,0.307114,0.008741,0.062651,0.914800,0.022549
2,c22adee811b6,0.045510,0.120446,0.000710,0.035032,0.130404,0.001230,0.046919,0.282703,0.003711,0.084444,0.245673,0.003216,0.211905,0.779227,0.008868
3,a10d361e54e4,0.034794,0.130030,0.001843,0.032867,0.131906,0.001894,0.111472,0.218984,0.002877,0.079594,0.249817,0.003922,0.258728,0.730738,0.010535
4,db3e453ec4e2,0.052472,0.113541,0.000653,0.069716,0.096213,0.000738,0.082594,0.249333,0.001406,0.114738,0.216559,0.002036,0.319521,0.675646,0.004833

In [13]:
from sklearn.metrics import log_loss

option = ''

local_score = log_loss(local_pred_df['label'].values, local_pred_df[['Ineffective'+option,'Adequate'+option,'Effective'+option]].values)
print('local_score = {:.4f}'.format(local_score))

kaggle_score = log_loss(local_pred_df['label'].values, kaggle_pred_df[['Ineffective'+option,'Adequate'+option,'Effective'+option]].values)
print('kaggle_score = {:.4f}'.format(kaggle_score))

local_score = 0.5795
kaggle_score = 0.5795